apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Confluent Control Center
name: cp-control-center
version: 0.1.0
dependencies:
  - name: cp-control-center
    version: "0.1.0"
    repository: "file://charts/cp-control-center-0.1.0.tgz"
